services:
  website-as-text:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - TARGET=https://stefvanwijchen.com
      - NODE_ENV=production
      - LIVE=true
    restart: unless-stopped
