services:
  website-as-text:
    build: .
    ports:
      - "3000:3000"
    environment:
      - TARGET=https://stefvanwijchen.com
      - NODE_ENV=production
      - LIVE=true
    restart: unless-stopped
